import {
  ShoppingBag, Carrot, Milk, Drumstick, Apple, Store, Smartphone,
  Package, Truck, Flame, Droplets, Coffee, Egg, Fish, 
  IceCream, Pizza, Wine, Beer, Cookie,
  CupSoda, Bone, Sprout, Wheat, Soup, Croissant, 
  Baby, PawPrint, Snail, Scissors, Shirt, Flower,
  Gift, Heart, Key, Lightbulb, Music, Palette,
  PenTool, Sun, Moon, Star, Umbrella,
  Video, Camera, Headset, Mic, BookOpen, Calculator,
  Compass, Map, Globe, Pill, Car, Bike, Glasses, Watch, 
  Zap,
  Ticket
} from 'lucide-react';

export const GONDOLA_ICONS = [
  { id: 'shoppingBag', label: 'Sacola', icon: ShoppingBag },
  { id: 'carrot', label: 'Cenoura', icon: Carrot },
  { id: 'milk', label: 'Leite', icon: Milk },
  { id: 'meat', label: 'Carnes', icon: Drumstick },
  { id: 'apple', label: 'Maçã', icon: Apple },
  { id: 'store', label: 'Loja', icon: Store },
  { id: 'smartphone', label: 'Eletrônicos', icon: Smartphone },
  { id: 'package', label: 'Caixa', icon: Package },
  { id: 'truck', label: 'Caminhão', icon: Truck },
  { id: 'flame', label: 'Chama', icon: Flame },
  { id: 'droplets', label: 'Água/Líquidos', icon: Droplets },
  { id: 'coffee', label: 'Café', icon: Coffee },
  { id: 'egg', label: 'Ovos', icon: Egg },
  { id: 'fish', label: 'Peixaria', icon: Fish },
  { id: 'iceCream', label: 'Sorvetes', icon: IceCream },
  { id: 'pizza', label: 'Pizza/Congelados', icon: Pizza },
  { id: 'wine', label: 'Vinhos', icon: Wine },
  { id: 'beer', label: 'Cervejas', icon: Beer },
  { id: 'cookie', label: 'Biscoitos', icon: Cookie },
  { id: 'cupSoda', label: 'Refrigerantes', icon: CupSoda },
  { id: 'bone', label: 'Pet Shop (Osso)', icon: Bone },
  { id: 'sprout', label: 'Plantas/Horta', icon: Sprout },
  { id: 'wheat', label: 'Grãos/Cereais', icon: Wheat },
  { id: 'soup', label: 'Sopas/Caldos', icon: Soup },
  { id: 'croissant', label: 'Padaria', icon: Croissant },
  { id: 'baby', label: 'Bebê', icon: Baby },
  { id: 'pawPrint', label: 'Pet Shop', icon: PawPrint },
  { id: 'snail', label: 'Pets/Jardim', icon: Snail },
  { id: 'scissors', label: 'Papelaria', icon: Scissors },
  { id: 'shirt', label: 'Roupas/Vestuário', icon: Shirt },
  { id: 'flower', label: 'Flores', icon: Flower },
  { id: 'gift', label: 'Presentes', icon: Gift },
  { id: 'heart', label: 'Saúde', icon: Heart },
  { id: 'key', label: 'Chaves/Ferramentas', icon: Key },
  { id: 'lightbulb', label: 'Lâmpadas/Elétrica', icon: Lightbulb },
  { id: 'music', label: 'Música', icon: Music },
  { id: 'palette', label: 'Artes/Pintura', icon: Palette },
  { id: 'penTool', label: 'Ferramentas', icon: PenTool },
  { id: 'sun', label: 'Verão', icon: Sun },
  { id: 'moon', label: 'Dormir/Noite', icon: Moon },
  { id: 'star', label: 'Destaques', icon: Star },
  { id: 'umbrella', label: 'Inverno/Chuva', icon: Umbrella },
  { id: 'video', label: 'Filmes', icon: Video },
  { id: 'camera', label: 'Câmeras', icon: Camera },
  { id: 'headset', label: 'Fones', icon: Headset },
  { id: 'mic', label: 'Áudio', icon: Mic },
  { id: 'bookOpen', label: 'Livros', icon: BookOpen },
  { id: 'calculator', label: 'Escritório', icon: Calculator },
  { id: 'compass', label: 'Aventura', icon: Compass },
  { id: 'map', label: 'Viagem', icon: Map },
  { id: 'globe', label: 'Importados', icon: Globe },
  { id: 'pill', label: 'Farmácia', icon: Pill },
  { id: 'car', label: 'Automotivo', icon: Car },
  { id: 'bike', label: 'Bicicletas', icon: Bike },
  { id: 'glasses', label: 'Óculos/Verão', icon: Glasses },
  { id: 'watch', label: 'Relógios/Acessórios', icon: Watch },
  { id: 'zap', label: 'Energéticos', icon: Zap },
  { id: 'ticket', label: 'Ingressos/Sorteios', icon: Ticket }
];

export const ICONS_MAP = GONDOLA_ICONS.reduce((acc, curr) => {
  acc[curr.id] = curr.icon;
  return acc;
}, {} as Record<string, any>);
